"$schema" = 'https://starship.rs/config-schema.json'
format = """$all $fill $cmd_duration
$character"""

add_newline = false

[character]
success_symbol = "[â¯](green)"
error_symbol = "[â¯](red)"

[cmd_duration]
min_time = 10
show_milliseconds = true
format = "[$duration](bright-black)"

[fill]
symbol = ' '

[python]
format = "via [ğŸ $version](bold green) "
symbol = "ğŸ "
pyenv_version_name = true
pyenv_prefix = "pyenv"

[golang]
symbol = "î™ "

[nodejs]
detect_extensions = []

[git_metrics]
disabled = false
format = '(([ï‘— $added ]($added_style))([ï‘˜ $deleted ]($deleted_style)))'
only_nonzero_diffs = true
added_style = 'green'
deleted_style = 'red'

[line_break]
disabled = true

[jobs]
disabled = true

[battery]
disabled = true

[env_var.SOFTWARE_UPDATE_AVAILABLE]
variable = 'SOFTWARE_UPDATE_AVAILABLE'
format = '[$env_value]($style)'
default = ''
style = 'cyan'

[env_var.DOTFILES_UPDATE_AVAILABLE]
variable = 'DOTFILES_UPDATE_AVAILABLE'
format = '[$env_value]($style)'
default = ''
style = 'cyan'